### ISSUE TITLE
Create a license

### ISSUE THREAD

**Issue by Zomis** [MohamedRejeb/Card-Game-Animation#1]
First of all, let me say thank you for an excellent demo application!

I was googling things like "compose card dealer animations" or "compose animate move card from one component to another" and trying to find examples like crazy until I eventually found your example by just googling "card game jetpack compose".

Now, I suspect it's not your intention, but right now I'm not allowed to copy any of your code and adapt to my own use.

Please check https://choosealicense.com/no-permission/ and choose an appropriate license. I would recommend something like Apache License 2.0 or MIT License for this project.

**Comment by MohamedRejeb** [comment]
Done, Thank you!
